---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: content
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: content
  policy:
    semver:
      range: 1.0.x
