---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: content
  namespace: flux-system
spec:
  image: 202581749740.dkr.ecr.eu-west-1.amazonaws.com/test
  interval: 1m0s
  secretRef:
    name: ecr-credentials
